### ISSUE TITLE
Revolt Mini link in readme is incorrect

### ISSUE THREAD

**Issue by retcinder** [upryzing/crescent#10]
https://github.com/upryzing/crescent/blob/3901f23e55331ebf8485d300a0ff7e7543e17b4f/README.md?plain=1#L30

codeberg.page not codeberg.org

**Comment by bloomdevelop** [comment]
Fixed on [latest commit (f2e6c0a)](https://github.com/upryzing/crescent/commit/f2e6c0af7aab08ed86379fa6976e8a41da66d8d1)

**Comment by amycatgirl** [comment]
oh um
lol i forgor


thanks bloom
